default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: startup_showcase_development

test:
  <<: *default
  database: startup_showcase_test
  
production:
  <<: *default
  database: startup_showcase_production
  username: startup_showcase
  password: <%= ENV['STARTUP_SHOWCASE_DATABASE_PASSWORD'] %>
