[
  {
    title: "Анализ Трафика", 
    description: "Программное обеспечение для анализа транспортных потоков по видео. Технология мониторинга может применяться как для учёта транспортных потоков, так и для адаптивного регулирования перекрёстков. Система способна определять ДТП, занятость парковочных мест, контролировать соблюдение правил дорожного движения, причём съёмка может проходить как со стационарных камер, так и с беспилотных летательных аппаратов. Точность определения объектов достигает 90%.",
    contact_name: "Иваонов Иван Иванович",
    direction: "Разрабатывает решения для мониторинга дорожного движения",
    phone_number: "88008003212",
    email: "traffic@mail.ru",
    legal_entity_title: "ООО Трафик аналитика",
    contact_rank: "Технический директор",
    inn: "3664069397",
    people_count: "4",
    site_url: "traffic.ru",
    telegram_url: "traffic.te",
    presentation_url: "traffic_presentation.pdf"
  },
  {
    title: "Road Vision", 
    description: "Решение адаптивного регулирования перекрёстков через анализ данных о транспортных средствах с видеопотоков дорожных камер, основанное на технологии компьютерного зрения и искусственного интеллекта. Продукт состоит из одноплатного компьютера с модулем компьютерного зрения, устанавливаемого на дорожную камеру. На основе данных, полученных с камер, отправляется сигнал на переключение светофорных фаз для регулирования перекрёстка. Основное преимущество решения в том, что все вычисления происходят на объекте и не требуют передачи больших данных в дата-центр, что значительно упрощает регулирование перекрёстка.",
    contact_name: "Денисов Даниил Максимович",
    direction: "Определение дорожных объектов",
    phone_number: "88003203212",
    email: "road_vision@mail.ru",
    legal_entity_title: "ООО Дорожное зрение",
    contact_rank: "Разработчик",
    inn: "366123427",
    people_count: "5",
    site_url: "road_vision.ru",
    telegram_url: "road_vision.te",
    presentation_url: "road_vision_presentation.pdf"
  },
  {
    title: "Пропускной пункт", 
    description: " Автоматизация для, контрольно-пропускной режим - это комплекс организационно-правовых ограничений и правил, устанавливающих порядок пропуска через контрольно-пропускные пункты в отдельные здания (помещения) сотрудников объекта, посетителей, транспорта и материальных средств. Контрольно-пропускной режим является одним из ключевых моментов в организации системы безопасности на предприятии.",
    contact_name: "Соколов Елисей Федотович",
    direction: "Разрабатывает решения для пропускного пункта",
    phone_number: "88004123212",
    email: "checkpoint@mail.ru",
    legal_entity_title: "ООО Трафик аналитика",
    contact_rank: "Технический директор",
    inn: "3424569397",
    people_count: "3",
    site_url: "checkpoint.ru",
    telegram_url: "checkpoint.te",
    presentation_url: "checkpoint_presentation.pdf"
  },
  {
    title: "Фонарик", 
    description: "Современные светофоры которые умеют синхронизироваться с соседними светофорами, работать по заложенной в них программе отдельно от других светофорных объектов, самостоятельно определять дорожную ситуацию и адаптироваться к ней. Например, определять, сколько перед ними по каким направлениям стоит автомобилей.",
    contact_name: "Константинов Виталий Семенович",
    direction: "Разрабатывает решения для регулирования дорожного движения",
    phone_number: "88014233212",
    email: "lamp@mail.ru",
    legal_entity_title: "ООО Трафик аналитика",
    contact_rank: "Разработчик",
    inn: "3642169397",
    people_count: "5",
    site_url: "lamp.ru",
    telegram_url: "lamp.te",
    presentation_url: "lamp_presentation.pdf"
  },
  {
    title: "Air Guard", 
    description: "Платформа комплексного мониторинга и управления микроклиматом в помещениях и на мобильных объектах. Сервис состоит: \n – из модульных климатических IoT-датчиков собственной разработки, конфигурируемых под потребности клиента;\n – облачного сервера, поддерживающего работу веб-интерфейса, мобильного приложения, API и чат-ботов.",
    contact_name: "Носов Влас Куприянович",
    direction: "Разрабатывает решения для мониторинга дорожного движения",
    phone_number: "88321003212",
    email: "air_guard@mail.ru",
    legal_entity_title: "ООО Трафик аналитика",
    contact_rank: "Менеджер",
    inn: "3664012493",
    people_count: "4",
    site_url: "air_guard.ru",
    telegram_url: "air_guard.te",
    presentation_url: "air_guard_presentation.pdf"
  }
]